spring.application.name=jenkins_test_build
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jinjnguyen147@gmail.com
spring.mail.password=zluy oxuv ezwy neor
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

